### ISSUE TITLE
Unable to create strategy on Linux

### ISSUE THREAD

**Issue by wheatdogg** [GimmerBot/Gimmer#124]
Expected Behaviour: Choose one of the strategies

Actual Behaviour: App returns error: Cannot read property 'name' of null.

Steps to Reproduce the Problem: Select strategy. Assign it a name. Agree to T&C. Click OK. Wait.

Specifications
 - Gimmer Version: 1.7.8
 - OS: Ubuntu 16.04 LTS (installed .deb package)
 - Date: Feb 12 2019
 
Printscreen (Case needed)
![screenshot from 2019-02-14 12-33-46](https://user-images.githubusercontent.com/23291971/52763007-f528f900-3054-11e9-9a86-bc45c8fc594d.png)

**Comment by wheatdogg** [comment]
Here's a follow-up to my last question. Ran Gimmer from the command line, and got this error:
<pre>module.js:545
    throw err;
    ^

Error: Cannot find module &apos;../dialog&apos;
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/usr/lib/gimmer/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/usr/lib/gimmer/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.&lt;anonymous&gt; (/usr/lib/gimmer/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)</pre>

I assume this is why I'm getting the "Cannot read" messages within the application, but I don't know how to fix the problem.
