### ISSUE TITLE
Changing coin pair doesn't change graph

### ISSUE THREAD

**Issue by ficovolante** [GimmerBot/Gimmer#2]
### Expected Behavior
Graph should display data from selected coin pair
### Actual Behavior
Changing the coin pair causes the graph to flash white then the same data (ETH/BTC) to be re-displayed. I'm also getting this error in the terminal:
```
May 16, 2018 6:05 PM: Server listening at port 55000
Error: Failed to lookup view "error" in views directory "/usr/lib/gimmer/resources/app.asar/app/views"
    at Function.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/response.js:1008:7)
    at app.(anonymous function) (/usr/lib/gimmer/resources/app.asar/app/app.js:136:119)
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at CustomErrorHandler.error (/usr/lib/gimmer/resources/app.asar/app/config/global.errors.js:63:32)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:51:45
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at Object.next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/route.js:127:14)
    at ExpressDriver.handleError (/usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:286:17)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/RoutingControllerExecutor.js:89:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Failed to lookup view "error" in views directory "/usr/lib/gimmer/resources/app.asar/app/views"
    at Function.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/response.js:1008:7)
    at app.(anonymous function) (/usr/lib/gimmer/resources/app.asar/app/app.js:136:119)
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at CustomErrorHandler.error (/usr/lib/gimmer/resources/app.asar/app/config/global.errors.js:63:32)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:51:45
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at Object.next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/route.js:127:14)
    at ExpressDriver.handleError (/usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:286:17)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/RoutingControllerExecutor.js:89:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Failed to lookup view "error" in views directory "/usr/lib/gimmer/resources/app.asar/app/views"
    at Function.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/response.js:1008:7)
    at app.(anonymous function) (/usr/lib/gimmer/resources/app.asar/app/app.js:136:119)
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at CustomErrorHandler.error (/usr/lib/gimmer/resources/app.asar/app/config/global.errors.js:63:32)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:51:45
    at Layer.handle_error (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:315:13)
    at /usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/index.js:275:10)
    at Object.next (/usr/lib/gimmer/resources/app.asar/node_modules/express/lib/router/route.js:127:14)
    at ExpressDriver.handleError (/usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/driver/ExpressDriver.js:286:17)
    at /usr/lib/gimmer/resources/app.asar/node_modules/routing-controllers/RoutingControllerExecutor.js:89:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
### Steps to Reproduce the Problem
See above.
### Specifications

    Gimmer Version: 0.2.1
    OS: Ubunutu 18.04
    Date: 16 May 2018

Printscreen (Case needed)

**Comment by modem7** [comment]
It does if you click save

**Comment by ficovolante** [comment]
I reaslised that I wasn't saving the strategy before running it. When I save, the chart is correctly showing the coin pair and data and Buy/Sell points. I think the chart is only showing the saved coin pair, rather than the coin pair that was used for the backtest.

**Comment by Flllexa** [comment]
Reviewed against Gimmer v3.0.414.

Changing the selected pair now replaces the rendered candle series and execution markers. Pair switching and chart re-rendering are covered by the current chart component tests.

Closing as fixed.
